import React, { useState, useEffect, useCallback } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import api from '../../utils/api';
import toast from 'react-hot-toast';
import { Wand2, Code2, MessageSquare, CheckCircle, BrainCircuit, ExternalLink, Settings, Lock, Square, CheckSquare, ChevronDown, ChevronUp, RefreshCw, Layers } from 'lucide-react';

// ─── Question Selection Card ──────────────────────────────────────────────────
const QuestionCard = ({ q, selected, onToggle, type = 'coding' }) => {
  const [expanded, setExpanded] = useState(false);
  const isCoding = type === 'coding';
  const color = isCoding ? 'blue' : 'green';

  return (
    <div className={`border rounded-2xl p-5 transition-all duration-300 ${selected ? `border-${color}-500 bg-${color}-500/5 shadow-lg shadow-${color}-500/10` : 'border-white/5 bg-white/5 hover:border-white/20 hover:bg-white/10'}`}>
      <div className="flex items-start justify-between gap-4">
        <div className="flex items-start gap-4 flex-1 min-w-0">
          <button onClick={() => onToggle(q)} className="mt-1 transition-transform active:scale-90">
             {selected ? <CheckSquare className={`text-${color}-500`} size={22}/> : <Square className="text-gray-600" size={22}/>}
          </button>
          <div className="min-w-0 flex-1">
             <div className="flex items-center gap-2 mb-2">
                <h4 className="font-bold text-white tracking-tight">{isCoding ? q.title : 'Interview Question'}</h4>
                <span className={`text-[9px] font-bold uppercase px-2 py-0.5 rounded-full border bg-${color}-500/10 text-${color}-400 border-${color}-500/20`}>{q.difficulty}</span>
             </div>
             <p className={`text-sm text-gray-400 leading-relaxed ${expanded ? '' : 'line-clamp-2'}`}>{isCoding ? q.description : q.question}</p>
          </div>
        </div>
        <button onClick={() => setExpanded(!expanded)} className="p-1 hover:bg-white/5 rounded-lg text-gray-500 transition-colors">
            {expanded ? <ChevronUp size={18}/> : <ChevronDown size={18}/>}
        </button>
      </div>

      {expanded && (
        <div className="mt-5 space-y-4 border-t border-white/5 pt-5 ml-9 animate-fade-in text-xs leading-relaxed">
          {isCoding ? (
            <>
              <div className="bg-[#0f1117] p-4 rounded-xl border border-white/5 font-mono text-purple-300 overflow-x-auto">
                 {q.function_signature}
              </div>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                 <div className="p-3 bg-green-500/5 border border-green-500/10 rounded-xl">
                    <p className="text-[10px] font-bold text-green-500 uppercase mb-2">Public Test Case</p>
                    <p className="font-mono text-gray-400 break-all">IN: {q.public_testcases?.[0]?.input}</p>
                    <p className="font-mono text-gray-400 break-all">OUT: {q.public_testcases?.[0]?.output}</p>
                 </div>
                 <div className="p-3 bg-blue-500/5 border border-blue-500/10 rounded-xl flex items-center gap-3">
                    <Lock size={16} className="text-blue-400 opacity-50"/>
                    <p className="text-gray-500 italic">3 hidden test cases secured for automated grading.</p>
                 </div>
              </div>
            </>
          ) : (
             <>
                <div className="p-4 bg-white/5 border border-white/10 rounded-xl space-y-3 text-sm">
                   <p className="text-gray-500 font-bold uppercase text-[10px]">Evaluation Keywords (NLP Targets)</p>
                   <div className="flex flex-wrap gap-2">
                     {q.keywords?.map(k => <span key={k} className="px-3 py-1 bg-white/5 border border-white/10 rounded-lg text-xs font-medium text-gray-300">{k}</span>)}
                   </div>
                </div>
             </>
          )}
        </div>
      )}
    </div>
  );
};

// ─── Main Component ───────────────────────────────────────────────────────────
const AssessmentBuilder = () => {
  const { jobId } = useParams();
  const navigate = useNavigate();
  
  const [job, setJob] = useState(null);
  const [loading, setLoading] = useState(false);
  const [fetching, setFetching] = useState(true);
  const [saving, setSaving] = useState(false);
  const [isLocked, setIsLocked] = useState(false);
  const [isConfirmed, setIsConfirmed] = useState(false);

  // Pools generated by AI
  const [codingPool, setCodingPool] = useState([]);
  const [interviewPool, setInterviewPool] = useState([]);
  
  // Custom Manual Questions
  const [manualCoding, setManualCoding] = useState([]);
  const [manualInterview, setManualInterview] = useState([]);
  
  // View Modes: 'ai' or 'manual'
  const [codingMode, setCodingMode] = useState('ai'); 
  const [interviewMode, setInterviewMode] = useState('ai');

  // Form states for manual entry
  const [showCodingForm, setShowCodingForm] = useState(false);
  const [showInterviewForm, setShowInterviewForm] = useState(false);
  
  const [newCoding, setNewCoding] = useState({ 
    title: '', description: '', function_signature: 'def solve(n: int) -> int:', 
    constraints: '', difficulty: 'Medium', 
    public_testcases: [{input:'', output:''}, {input:'', output:''}], 
    hidden_testcases: [{input:'', output:''}, {input:'', output:''}, {input:'', output:''}] 
  });
  const [newInterview, setNewInterview] = useState({ 
    question: '', difficulty: 'Medium', keywords: [], expected_points: [] 
  });

  const fetchJob = useCallback(async () => {
    try {
      const res = await api.get(`/jobs/${jobId}`);
      if (!res.data || !res.data.config_json) {
          throw new Error("Invalid job data");
      }
      setJob(res.data);
      
      const configRes = await api.get(`/hiring-ai/config/${jobId}`);
      if (configRes.data?.data?.status === 'locked') {
         setIsLocked(true);
         setIsConfirmed(true);
      }
    } catch (err) {
      toast.error('Failed to load job configuration');
      navigate('/hiring-dashboard');
    } finally {
      setFetching(false);
    }
  }, [jobId, navigate]);

  useEffect(() => { fetchJob(); }, [fetchJob]);

  const handleAddManualCoding = () => {
    if (!newCoding.title || !newCoding.description) return toast.error("Please fill required fields");
    setManualCoding([...manualCoding, { ...newCoding, id: `manual-${Date.now()}` }]);
    setShowCodingForm(false);
    setNewCoding({ title: '', description: '', function_signature: 'def solve(n: int) -> int:', constraints: '', difficulty: 'Medium', public_testcases: [{input:'', output:''}, {input:'', output:''}], hidden_testcases: [{input:'', output:''}, {input:'', output:''}, {input:'', output:''}] });
    toast.success("Manual coding problem added to pool.");
  };

  const handleAddManualInterview = () => {
    if (!newInterview.question) return toast.error("Question text is required");
    setManualInterview([...manualInterview, { ...newInterview, id: `manual-${Date.now()}` }]);
    setShowInterviewForm(false);
    setNewInterview({ question: '', difficulty: 'Medium', keywords: [], expected_points: [] });
    toast.success("Manual interview question added to pool.");
  };

  const handleGenerate = async () => {
    if (!job) return;
    setLoading(true);
    const tid = toast.loading('Initiating AI Generation Engine...');
    
    const codingEnabled = job?.config_json?.rounds?.coding?.enabled;
    const interviewEnabled = job?.config_json?.rounds?.interview?.enabled;

    const getDistribution = (diff, total) => {
        if (diff === 'Easy') return { easy: Math.floor(total * 0.7), medium: Math.ceil(total * 0.3), hard: 0 };
        if (diff === 'Hard') return { easy: 0, medium: Math.ceil(total * 0.3), hard: Math.floor(total * 0.7) };
        // Balanced for Medium
        return { easy: Math.floor(total/3), medium: Math.floor(total/3) + (total%3), hard: Math.floor(total/3) };
    };

    const payloadBase = {
        role: job?.title,
        topics: [...(job?.skills_required || []), ...(job?.config_json?.rounds?.coding?.topics || [])].slice(0, 5),
        total_questions: 6 
    };

    try {
      const requests = [];
      if (codingEnabled) {
          const diff = job?.config_json?.rounds?.coding?.difficulty || 'Medium';
          requests.push(api.post('/hiring-ai/generate/coding', { 
              ...payloadBase, 
              difficulty_distribution: getDistribution(diff, 6)
          }));
      }
      if (interviewEnabled) {
          const diff = job?.config_json?.rounds?.interview?.difficulty || 'Medium';
          requests.push(api.post('/hiring-ai/generate/interview', { 
              ...payloadBase, 
              difficulty_distribution: getDistribution(diff, 6)
          }));
      }

      const results = await Promise.all(requests);
      
      let resIdx = 0;
      if (codingEnabled) {
          setCodingPool(results[resIdx].data.data);
          setSelectedCoding([]);
          resIdx++;
      }
      if (interviewEnabled) {
          setInterviewPool(results[resIdx].data.data);
          setSelectedInterview([]);
      }

      toast.success('AI successfully mapped knowledge bounds and generated pools.', { id: tid });
    } catch (err) {
      toast.error('LLM Generation Failed. Resource Exhausted or Invalid Key.', { id: tid });
    } finally {
      setLoading(false);
    }
  };

  const handleConfirm = async () => {
    const interviewCount = job?.config_json?.rounds?.interview?.enabled ? job?.config_json?.rounds?.interview?.questions : 0;
    const codingCount = job?.config_json?.rounds?.coding?.enabled ? job?.config_json?.rounds?.coding?.questions : 0;

    if (selectedCoding.length !== codingCount) {
        toast.error(`Please select exactly ${codingCount} coding question(s).`);
        return;
    }
    if (selectedInterview.length !== interviewCount) {
        toast.error(`Please select exactly ${interviewCount} interview question(s).`);
        return;
    }

    setSaving(true);
    const tid = toast.loading('Saving selection...');
    try {
        await api.post('/hiring-ai/save-config', {
            job_id: jobId,
            coding_questions: selectedCoding,
            interview_questions: selectedInterview
        });
        setIsConfirmed(true);
        toast.success('Selection Confirmed! You can now lock the assessment.', { id: tid });
    } catch (err) {
        toast.error('Failed to confirm selection.', { id: tid });
    } finally {
        setSaving(false);
    }
  };

  const handleLock = async () => {
      setSaving(true);
      const tid = toast.loading('Locking Assessment...');
      try {
          await api.post('/hiring-ai/lock-config', { job_id: jobId });
          setIsLocked(true);
          toast.success('Assessment Locked & Ready for Deployment!', { id: tid });
          navigate('/hiring-dashboard');
      } catch (err) {
          toast.error('Failed to lock assessment.', { id: tid });
      } finally {
          setSaving(false);
      }
  };

  const toggleSelection = (q, type) => {
      if (isLocked) {
          toast.error("Assessment is locked. No further changes can be made.");
          return;
      }
      setIsConfirmed(false);
      const isCoding = type === 'coding';
      const max = isCoding ? job?.config_json?.rounds?.coding?.questions : job?.config_json?.rounds?.interview?.questions;
      const setter = isCoding ? setSelectedCoding : setSelectedInterview;
      
      const qKey = isCoding ? q.title : q.question;
      
      setter(prev => {
          const exists = prev.find(item => (isCoding ? item.title === qKey : item.question === qKey));
          if (exists) return prev.filter(item => (isCoding ? item.title !== qKey : item.question !== qKey));
          if (prev.length >= max) {
              toast.error(`Limit reached for this round (${max} Qs).`);
              return prev;
          }
          return [...prev, q];
      });
  };

  // Selection state
  const [selectedCoding, setSelectedCoding] = useState([]);
  const [selectedInterview, setSelectedInterview] = useState([]);

  if (fetching) return <div className="p-20 text-center"><RefreshCw className="animate-spin text-primary-500 mx-auto mb-4"/> Loading Sandbox Parameters...</div>;
  if (!job) return <div className="p-20 text-center text-gray-500 tracking-widest uppercase">System Initialization Failure. Please Refresh.</div>;

  const config = job?.config_json?.rounds || {};

  return (
    <div className="animate-fade-in max-w-[1240px] mx-auto pb-20 px-6 text-white">
      {/* Header Info */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-end gap-6 mb-12 pt-4">
        <div className="space-y-2">
            <h1 className="text-4xl font-extrabold tracking-tight flex items-center gap-4"><BrainCircuit className="text-purple-400" size={38}/> AI Assessment Lab</h1>
            <p className="text-gray-400 font-medium">Finalizing exam for <span className="text-blue-400">{job.title}</span> • {job.company_name}</p>
        </div>
        <div className="flex gap-4">
            <button onClick={() => navigate('/hiring-dashboard')} className="px-6 py-2.5 bg-dark-bg border border-white/5 hover:bg-white/5 rounded-2xl font-bold transition-all">Back</button>
            
            {isLocked ? (
                <div className="px-8 py-2.5 bg-gray-800 rounded-2xl font-extrabold flex items-center gap-2 border border-white/10 text-gray-400">
                    <Lock size={20}/> Assessment Locked
                </div>
            ) : !isConfirmed ? (
                <button onClick={handleConfirm} disabled={saving || loading || selectedCoding.length !== (job?.config_json?.rounds?.coding?.enabled ? job?.config_json?.rounds?.coding?.questions : 0) || selectedInterview.length !== (job?.config_json?.rounds?.interview?.enabled ? job?.config_json?.rounds?.interview?.questions : 0)} className="px-8 py-2.5 bg-blue-600 hover:bg-blue-500 rounded-2xl font-extrabold shadow-lg shadow-blue-900/30 transition-all flex items-center gap-2 group active:scale-95 disabled:opacity-50">
                    {saving ? 'Confirming...' : <><CheckCircle size={20}/> Confirm Selection</>}
                </button>
            ) : (
                <button onClick={handleLock} disabled={saving || loading} className="px-8 py-2.5 bg-green-600 hover:bg-green-500 rounded-2xl font-extrabold shadow-lg shadow-green-900/30 transition-all flex items-center gap-2 group active:scale-95 disabled:opacity-50">
                   {saving ? 'Locking...' : <><Lock size={20}/> Lock & Deploy Assessment</>}
                </button>
            )}
        </div>
      </div>

      {/* READ-ONLY SOURCE OF TRUTH SUMMARY */}
      <div className="grid grid-cols-1 lg:grid-cols-4 gap-6 mb-12">
          <div className="lg:col-span-3 glass-panel p-8 rounded-[2rem] border-white/5 bg-white/5 flex flex-wrap gap-12 relative overflow-hidden">
             <div className="absolute top-0 right-0 p-8 opacity-5"><Settings size={80}/></div>
             
             <div className="space-y-2">
                <p className="text-[10px] font-bold text-gray-500 uppercase tracking-widest">Job Bounds</p>
                <div className="flex items-center gap-2">
                    <span className="px-3 py-1 bg-white/10 rounded-lg text-xs font-bold">{job.experience_level}</span>
                    <span className="px-3 py-1 bg-white/10 rounded-lg text-xs font-bold">{job.config_json.work_mode}</span>
                </div>
             </div>

             {config?.interview?.enabled && (
                <div className="space-y-2">
                    <p className="text-[10px] font-bold text-green-500/80 uppercase tracking-widest flex items-center gap-2"><Layers size={10}/> Interview Config</p>
                    <div className="text-sm font-bold">{config?.interview?.questions || 0} Questions • {config?.interview?.difficulty || 'N/A'}</div>
                    <p className="text-[10px] text-gray-500">{config?.interview?.think_time || 0}s / {config?.interview?.answer_time || 0}s limit</p>
                </div>
             )}

             {config?.coding?.enabled && (
                <div className="space-y-2 border-l border-white/10 pl-12">
                    <p className="text-[10px] font-bold text-blue-500/80 uppercase tracking-widest flex items-center gap-2"><Code2 size={10}/> Coding Lab Config</p>
                    <div className="text-sm font-bold">{config?.coding?.questions || 0} Questions • {config?.coding?.difficulty || 'N/A'}</div>
                    <p className="text-[10px] text-gray-500">{config?.coding?.total_time || 0} Min Total</p>
                </div>
             )}

             {config?.proctoring && (
                <div className="space-y-2 border-l border-white/10 pl-12">
                    <p className="text-[10px] font-bold text-red-500/80 uppercase tracking-widest">Proctoring</p>
                    <div className="text-sm font-bold">{config?.proctoring?.warning_limit || 0} Warnings</div>
                    <p className="text-[10px] text-gray-500">Scan every {config?.proctoring?.scan_interval || 0}s</p>
                </div>
             )}
          </div>

          <div className="flex items-center justify-center">
             <button onClick={handleGenerate} disabled={loading || isLocked} className={`w-full h-full py-6 rounded-[2rem] border-2 border-dashed transition-all flex flex-col items-center justify-center gap-3 ${loading || isLocked ? 'border-purple-500/30 bg-purple-500/5 opacity-50' : 'border-purple-500/30 hover:border-purple-500/60 hover:bg-purple-500/10'}`}>
                {loading ? <RefreshCw className="animate-spin text-purple-400" size={32}/> : <Wand2 className="text-purple-400 group-hover:scale-110" size={32}/>}
                <div className="text-center">
                    <p className="font-bold text-sm">{codingPool.length > 0 ? 'Regenerate Pools' : 'Generate Full Pack'}</p>
                    <p className="text-[10px] text-gray-500 mt-1">{isLocked ? 'Assessment Locked' : 'Multi-Stage AI Logic'}</p>
                </div>
             </button>
          </div>
      </div>

      <div className="grid grid-cols-1 xl:grid-cols-2 gap-12">
          {/* Coding Questions Selection */}
          <div className="space-y-6">
              <div className="flex justify-between items-end border-b border-white/5 pb-4">
                  <div className="space-y-1">
                    <h3 className="text-xl font-bold flex items-center gap-3"><Code2 className="text-blue-400"/> Coding Questions</h3>
                    <div className="flex items-center gap-4 mt-2">
                        <button onClick={() => setCodingMode('ai')} className={`text-[10px] font-bold uppercase tracking-widest px-3 py-1 rounded-lg border ${codingMode === 'ai' ? 'bg-blue-500/10 border-blue-500/30 text-blue-400' : 'bg-white/5 border-white/5 text-gray-500 hover:text-gray-300'}`}>AI Pool</button>
                        <button onClick={() => setCodingMode('manual')} className={`text-[10px] font-bold uppercase tracking-widest px-3 py-1 rounded-lg border ${codingMode === 'manual' ? 'bg-blue-500/10 border-blue-500/30 text-blue-400' : 'bg-white/5 border-white/5 text-gray-500 hover:text-gray-300'}`}>Manual Entry</button>
                    </div>
                  </div>
                  {config.coding.enabled && (
                    <div className={`px-4 py-1.5 rounded-full text-xs font-black uppercase tracking-widest ${selectedCoding.length === config.coding.questions ? 'bg-green-500/20 text-green-400' : 'bg-white/5 text-gray-600'}`}>
                        {selectedCoding.length} / {config.coding.questions} Selected
                    </div>
                  )}
              </div>

              {!config.coding.enabled ? (
                  <div className="p-12 text-center bg-white/5 rounded-3xl border border-white/5 opacity-40 italic text-gray-500">Technical round disabled in job settings.</div>
              ) : codingMode === 'manual' ? (
                  <div className="space-y-4">
                      {showCodingForm ? (
                          <div className="p-6 bg-white/5 border border-blue-500/20 rounded-[2rem] space-y-4 animate-fade-in">
                              <input type="text" placeholder="Problem Title" className="w-full bg-black/40 border border-white/10 rounded-xl px-4 py-2 text-sm" value={newCoding.title} onChange={e => setNewCoding({...newCoding, title: e.target.value})}/>
                              <textarea placeholder="Description" className="w-full bg-black/40 border border-white/10 rounded-xl px-4 py-2 text-sm h-24" value={newCoding.description} onChange={e => setNewCoding({...newCoding, description: e.target.value})}/>
                              <input type="text" placeholder="Function Signature" className="w-full bg-[#0f1117] border border-white/10 rounded-xl px-4 py-2 text-xs font-mono text-purple-400" value={newCoding.function_signature} onChange={e => setNewCoding({...newCoding, function_signature: e.target.value})}/>
                              
                              <div className="space-y-2">
                                <p className="text-xs font-bold text-gray-400">Public Test Cases</p>
                                {[0, 1].map(i => (
                                  <div key={`pub-${i}`} className="flex gap-2">
                                    <input type="text" placeholder={`Input ${i+1}`} className="w-1/2 bg-black/40 border border-white/10 rounded-xl px-4 py-2 text-sm font-mono" value={newCoding.public_testcases[i]?.input || ''} onChange={e => { const tc = [...newCoding.public_testcases]; if (!tc[i]) tc[i]={input:'', output:''}; tc[i].input = e.target.value; setNewCoding({...newCoding, public_testcases: tc}); }}/>
                                    <input type="text" placeholder={`Expected Output ${i+1}`} className="w-1/2 bg-black/40 border border-white/10 rounded-xl px-4 py-2 text-sm font-mono" value={newCoding.public_testcases[i]?.output || ''} onChange={e => { const tc = [...newCoding.public_testcases]; if (!tc[i]) tc[i]={input:'', output:''}; tc[i].output = e.target.value; setNewCoding({...newCoding, public_testcases: tc}); }}/>
                                  </div>
                                ))}
                              </div>
                              
                              <div className="space-y-2">
                                <p className="text-xs font-bold text-gray-400">Hidden Test Cases</p>
                                {[0, 1, 2].map(i => (
                                  <div key={`hid-${i}`} className="flex gap-2">
                                    <input type="text" placeholder={`Input ${i+1}`} className="w-1/2 bg-black/40 border border-white/10 rounded-xl px-4 py-2 text-sm font-mono" value={newCoding.hidden_testcases[i]?.input || ''} onChange={e => { const tc = [...newCoding.hidden_testcases]; if (!tc[i]) tc[i]={input:'', output:''}; tc[i].input = e.target.value; setNewCoding({...newCoding, hidden_testcases: tc}); }}/>
                                    <input type="text" placeholder={`Expected Output ${i+1}`} className="w-1/2 bg-black/40 border border-white/10 rounded-xl px-4 py-2 text-sm font-mono" value={newCoding.hidden_testcases[i]?.output || ''} onChange={e => { const tc = [...newCoding.hidden_testcases]; if (!tc[i]) tc[i]={input:'', output:''}; tc[i].output = e.target.value; setNewCoding({...newCoding, hidden_testcases: tc}); }}/>
                                  </div>
                                ))}
                              </div>

                              <div className="flex gap-4 pt-2">
                                  <button onClick={handleAddManualCoding} className="flex-1 bg-blue-600 py-2 rounded-xl text-xs font-bold">Add to Selection Pool</button>
                                  <button onClick={() => setShowCodingForm(false)} className="px-4 py-2 bg-white/5 rounded-xl text-xs font-bold text-gray-400">Cancel</button>
                              </div>
                          </div>
                      ) : (
                          <button onClick={() => { if(!isLocked) setShowCodingForm(true); }} disabled={isLocked} className={`w-full py-4 border-2 border-dashed border-white/10 rounded-[2rem] text-sm text-gray-500 transition-all ${isLocked ? 'opacity-50 cursor-not-allowed' : 'hover:bg-white/5'}`}>+ Add New Custom Question</button>
                      )}
                      
                      {manualCoding.map((q, i) => (
                           <QuestionCard key={i} q={q} type="coding" selected={selectedCoding.find(s=>s.title === q.title)} onToggle={(q) => toggleSelection(q, 'coding')}/>
                      ))}
                      {manualCoding.length === 0 && !showCodingForm && <p className="text-center text-xs text-gray-600 py-10 italic">Your custom question library is empty.</p>}
                  </div>
              ) : codingPool.length === 0 ? (
                  <div className="p-20 text-center bg-white/5 rounded-[2.5rem] border-2 border-dashed border-white/5 text-gray-600 font-bold animate-pulse">Awaiting AI Pulse... Click Generate above.</div>
              ) : (
                  <div className="space-y-4 max-h-[1000px] overflow-y-auto px-2 custom-scrollbar">
                      {codingPool.map((q, i) => (
                          <QuestionCard key={i} q={q} type="coding" selected={selectedCoding.find(s=>s.title === q.title)} onToggle={(q) => toggleSelection(q, 'coding')}/>
                      ))}
                  </div>
              )}
          </div>

          {/* Interview Questions Selection */}
          <div className="space-y-6">
              <div className="flex justify-between items-end border-b border-white/5 pb-4">
                  <div className="space-y-1">
                    <h3 className="text-xl font-bold flex items-center gap-3"><MessageSquare className="text-green-400"/> Interview Questions</h3>
                    <div className="flex items-center gap-4 mt-2">
                        <button onClick={() => setInterviewMode('ai')} className={`text-[10px] font-bold uppercase tracking-widest px-3 py-1 rounded-lg border ${interviewMode === 'ai' ? 'bg-green-500/10 border-green-500/30 text-green-400' : 'bg-white/5 border-white/5 text-gray-500 hover:text-gray-300'}`}>AI Pool</button>
                        <button onClick={() => setInterviewMode('manual')} className={`text-[10px] font-bold uppercase tracking-widest px-3 py-1 rounded-lg border ${interviewMode === 'manual' ? 'bg-green-500/10 border-green-500/30 text-green-400' : 'bg-white/5 border-white/5 text-gray-500 hover:text-gray-300'}`}>Manual Entry</button>
                    </div>
                  </div>
                  {config.interview.enabled && (
                    <div className={`px-4 py-1.5 rounded-full text-xs font-black uppercase tracking-widest ${selectedInterview.length === config.interview.questions ? 'bg-green-500/20 text-green-400' : 'bg-white/5 text-gray-600'}`}>
                        {selectedInterview.length} / {config.interview.questions} Selected
                    </div>
                  )}
              </div>

              {!config.interview.enabled ? (
                  <div className="p-12 text-center bg-white/5 rounded-3xl border border-white/5 opacity-40 italic text-gray-500">Speech round disabled in job settings.</div>
              ) : interviewMode === 'manual' ? (
                  <div className="space-y-4">
                      {showInterviewForm ? (
                          <div className="p-6 bg-white/5 border border-green-500/20 rounded-[2rem] space-y-4 animate-fade-in">
                              <textarea placeholder="Interview Question text..." className="w-full bg-black/40 border border-white/10 rounded-xl px-4 py-4 text-sm h-32" value={newInterview.question} onChange={e => setNewInterview({...newInterview, question: e.target.value})}/>
                              <div className="flex gap-4">
                                  <button onClick={handleAddManualInterview} className="flex-1 bg-green-600 py-2 rounded-xl text-xs font-bold">Add to Selection Pool</button>
                                  <button onClick={() => setShowInterviewForm(false)} className="px-4 py-2 bg-white/5 rounded-xl text-xs font-bold text-gray-400">Cancel</button>
                              </div>
                          </div>
                      ) : (
                          <button onClick={() => { if(!isLocked) setShowInterviewForm(true); }} disabled={isLocked} className={`w-full py-4 border-2 border-dashed border-white/10 rounded-[2rem] text-sm text-gray-500 transition-all ${isLocked ? 'opacity-50 cursor-not-allowed' : 'hover:bg-white/5'}`}>+ Add New Manual Question</button>
                      )}
                      
                      {manualInterview.map((q, i) => (
                           <QuestionCard key={i} q={q} type="interview" selected={selectedInterview.find(s=>s.question === q.question)} onToggle={(q) => toggleSelection(q, 'interview')}/>
                      ))}
                      {manualInterview.length === 0 && !showInterviewForm && <p className="text-center text-xs text-gray-600 py-10 italic">No manual questions added yet.</p>}
                  </div>
              ) : interviewPool.length === 0 ? (
                  <div className="p-20 text-center bg-white/5 rounded-[2.5rem] border-2 border-dashed border-white/5 text-gray-600 font-bold animate-pulse">Awaiting AI Pulse... Click Generate above.</div>
              ) : (
                  <div className="space-y-4 max-h-[1000px] overflow-y-auto px-2 custom-scrollbar">
                      {interviewPool.map((q, i) => (
                          <QuestionCard key={i} q={q} type="interview" selected={selectedInterview.find(s=>s.question === q.question)} onToggle={(q) => toggleSelection(q, 'interview')}/>
                      ))}
                  </div>
              )}
          </div>
      </div>
    </div>
  );
};

export default AssessmentBuilder;
