import React, { useState, useEffect } from 'react';
import { Search, MapPin, Briefcase, ChevronRight, X, Upload } from 'lucide-react';
import { Badge } from '../../components/ui/Badge';
import api from '../../utils/api';
import toast from 'react-hot-toast';

const JobMarketplace = () => {
  const [jobs, setJobs] = useState([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState('');
  const [selectedJob, setSelectedJob] = useState(null);
  
  // Apply Modal state
  const [resumeUrl, setResumeUrl] = useState('');
  const [applying, setApplying] = useState(false);

  useEffect(() => {
    fetchJobs();
  }, []);

  const fetchJobs = async () => {
    try {
      const { data } = await api.get('/jobs/public');
      setJobs(data);
    } catch (err) {
      toast.error('Failed to load jobs');
    } finally {
      setLoading(false);
    }
  };

  const filteredJobs = jobs.filter(j => j.title.toLowerCase().includes(search.toLowerCase()) || j.department.toLowerCase().includes(search.toLowerCase()));

  const handleApply = async () => {
    if (!resumeUrl) return toast.error("Please provide a resume URL for this demo.");
    setApplying(true);
    try {
      await api.post('/applications/apply', { job_id: selectedJob.id, resume_url: resumeUrl });
      toast.success("Application submitted successfully!");
      setSelectedJob(null);
      setResumeUrl('');
    } catch (err) {
      toast.error(err.response?.data?.detail || "Failed to apply");
    } finally {
      setApplying(false);
    }
  };

  return (
    <div className="animate-fade-in relative">
      {/* Header Search */}
      <div className="text-center mb-10 mt-6">
        <h1 className="text-4xl font-bold text-white mb-4">Find Your Next Role</h1>
        <p className="text-gray-400 max-w-2xl mx-auto mb-8">Browse curated opportunities generated by top startups and enterprises using AIHire.</p>
        <div className="relative max-w-2xl mx-auto group">
          <Search className="absolute left-4 top-1/2 -translate-y-1/2 text-gray-500 group-focus-within:text-primary-400 transition-colors" size={20} />
          <input 
            type="text" 
            placeholder="Search by job title, department, or keywords..."
            className="w-full bg-dark-surface/80 border border-white/10 hover:border-white/20 focus:border-primary-500 rounded-full py-4 pl-12 pr-6 text-white outline-none shadow-2xl backdrop-blur-xl transition-all"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
          />
        </div>
      </div>

      {loading ? (
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
          {[1,2,3,4,5,6].map(i => <div key={i} className="h-48 glass-panel rounded-2xl animate-pulse"></div>)}
        </div>
      ) : (
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
          {filteredJobs.map(job => (
            <div key={job.id} onClick={() => setSelectedJob(job)} className="glass-panel p-6 rounded-2xl cursor-pointer group hover:-translate-y-1 transition-transform duration-300">
              <div className="flex justify-between items-start mb-4">
                <div className="p-3 bg-gradient-to-br from-primary-500/20 to-accent-500/20 border border-white/10 rounded-xl text-primary-300 group-hover:scale-110 transition-transform">
                  <Briefcase size={24} />
                </div>
                <Badge variant="neutral">{job.experience_level}</Badge>
              </div>
              <h3 className="text-xl font-bold text-white mb-1 group-hover:text-primary-400 transition-colors">{job.title}</h3>
              <p className="text-sm text-gray-400 mb-4">{job.department}</p>
              
              <div className="flex flex-wrap gap-2 mb-6">
                {job.skills_required.slice(0,3).map(s => <span key={s} className="px-2 py-0.5 text-[10px] uppercase font-bold bg-dark-bg border border-white/5 rounded text-gray-300">{s}</span>)}
                {job.skills_required.length > 3 && <span className="px-2 py-0.5 text-[10px] uppercase font-bold bg-dark-bg border border-white/5 rounded text-gray-500">+{job.skills_required.length - 3}</span>}
              </div>

              <div className="flex justify-between items-center pt-4 border-t border-white/5">
                <span className="text-xs text-gray-500 flex items-center gap-1"><MapPin size={12}/> Remote</span>
                <button className="text-primary-400 text-sm font-medium flex items-center gap-1 group-hover:translate-x-1 transition-transform">View <ChevronRight size={16}/></button>
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Details/Apply Modal */}
      {selectedJob && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm animate-in fade-in zoom-in-95 duration-200">
          <div className="bg-dark-surface w-full max-w-2xl rounded-2xl border border-white/10 shadow-2xl p-6 sm:p-8 relative max-h-[90vh] overflow-y-auto">
            <button onClick={() => setSelectedJob(null)} className="absolute top-4 right-4 p-2 bg-dark-bg hover:bg-white/10 rounded-full text-gray-400 transition-colors"><X size={20}/></button>
            <Badge variant="primary" className="mb-4">{selectedJob.department}</Badge>
            <h2 className="text-3xl font-bold text-white mb-2">{selectedJob.title}</h2>
            <div className="flex items-center gap-4 text-sm text-gray-400 mb-6">
              <span className="flex items-center gap-1"><MapPin size={14}/> Remote</span>
              <span className="flex items-center gap-1"><Briefcase size={14}/> {selectedJob.experience_level}</span>
            </div>

            <div className="space-y-6 mb-8">
              <div>
                <h3 className="text-lg font-bold text-white mb-2">About the Role</h3>
                <p className="text-gray-300 leading-relaxed text-sm whitespace-pre-wrap">{selectedJob.description}</p>
              </div>
              <div>
                <h3 className="text-lg font-bold text-white mb-2">Required Skills</h3>
                <div className="flex flex-wrap gap-2">
                  {selectedJob.skills_required.map(s => <span key={s} className="px-3 py-1 bg-dark-bg border border-white/5 rounded-full text-sm text-gray-200">{s}</span>)}
                </div>
              </div>
            </div>

            <div className="p-5 bg-dark-bg/50 border border-primary-500/30 rounded-xl space-y-4">
              <h3 className="text-md font-bold text-white flex items-center gap-2"><Upload size={16} className="text-primary-400"/> Attach Resume</h3>
              <p className="text-xs text-gray-400">For this simulation, paste a URL referencing your document (e.g. Google Drive link or raw text string). Supabase Storage integration can be added later.</p>
              <input 
                type="text" 
                value={resumeUrl}
                onChange={e => setResumeUrl(e.target.value)}
                placeholder="https://docs.google.com/.../resume.pdf"
                className="w-full bg-dark-surface border border-white/10 focus:border-primary-500 rounded-lg p-3 text-sm text-white outline-none"
              />
              <button onClick={handleApply} disabled={applying} className="w-full btn-primary py-3 flex justify-center text-sm">{applying ? "Submitting..." : "Apply Now"}</button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default JobMarketplace;
